### ISSUE TITLE
Task 11.2

### ISSUE THREAD

**Issue by kvaleriy** [natenka/pyneng-examples-exercises#10]
Task 11.2 with modules doesn't work with python 3.8. Python returns error:
/usr/bin/python3 /Users/Retina/PycharmProjects/python-start/Play.py
{('R1', 'Eth0/0'): ('SW1', 'Eth0/1'),
 ('R2', 'Eth0/0'): ('SW1', 'Eth0/2'),
 ('R2', 'Eth0/1'): ('SW2', 'Eth0/11'),
 ('R3', 'Eth0/0'): ('SW1', 'Eth0/3'),
 ('R3', 'Eth0/1'): ('R4', 'Eth0/0'),
 ('R3', 'Eth0/2'): ('R5', 'Eth0/0'),
 ('R6', 'Eth0/1'): ('SW1', 'Eth0/5')}
Traceback (most recent call last):
  File "/Users/Retina/Library/Python/3.8/lib/python/site-packages/graphviz/backend.py", line 164, in run
    proc = subprocess.Popen(cmd, startupinfo=get_startupinfo(), **kwargs)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
**FileNotFoundError: [Errno 2] No such file or directory: 'dot'**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Retina/PycharmProjects/python-start/Play.py", line 28, in <module>
    draw_topology(topology)
  File "/Users/Retina/PycharmProjects/python-start/draw_network_graph.py", line 74, in draw_topology
    filename = g1.render(filename=output_filename)
  File "/Users/Retina/Library/Python/3.8/lib/python/site-packages/graphviz/files.py", line 207, in render
    rendered = backend.render(self._engine, format, filepath,
  File "/Users/Retina/Library/Python/3.8/lib/python/site-packages/graphviz/backend.py", line 221, in render
    run(cmd, capture_output=True, cwd=cwd, check=True, quiet=quiet)
  File "/Users/Retina/Library/Python/3.8/lib/python/site-packages/graphviz/backend.py", line 167, in run
    raise ExecutableNotFound(cmd)
graphviz.backend.ExecutableNotFound: failed to execute ['dot', '-Tsvg', '-O', 'topology'], make sure the Graphviz executables are on your systems' PATH

Process finished with exit code 1

I assume that error **FileNotFoundError: [Errno 2] No such file or directory: 'dot'** is key here. But I did try to define filename as:
sh_cdp_n_sw1
sh_cdp_n_sw1.txt
/Users/Retina/PycharmProjects/python-start/sh_cdp_n_sw1
/Users/Retina/PycharmProjects/python-start/sh_cdp_n_sw1.txt

None of them works.

Error: **make sure the Graphviz executables are on your systems' PATH** I believe I resolved by installing module for specific python version with command _python3 -m pip install grphviz_.

**Comment by pyneng** [comment]
The task states that you need to install both the module for Python and the graphviz package itself

> Для выполнения этого задания, должен быть установлен graphviz:
> apt-get install graphviz
> И модуль python для работы с graphviz:
> pip install graphviz

**Comment by kvaleriy** [comment]
I use macos with pycharm.

Retina@MacBook-Pro-python-start % python3 -m pip install graphviz
Requirement already satisfied: graphviz in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (0.14.2)
Retina@MacBook-Pro python-start % apt-get install graphviz
zsh: command not found: apt-get
Retina@MacBook-Pro python-start % 

Module graphviz installed for python 2.7 and for python3.9 which I use, in virtual environment as well. application apt-get is not available on my mac, but with brew it is installed as well.

**Comment by pyneng** [comment]
All examples in the book are shown in debian, hence the apt-get.

[Maybe there is something useful here](https://stackoverflow.com/questions/54966989/where-do-i-add-graphvizs-executable-on-a-mac
)
I can’t help, unfortunately, I don’t have a Mac OS, you have to [google it](https://www.google.ru/search?q=graphviz+macos++No+such+file+or+directory:+%27dot%27+site:stackoverflow.com&newwindow=1&sa=X&ved=2ahUKEwim1eDlivjsAhVslYsKHdhnCc8QrQIoBHoECAMQBQ&biw=1000&bih=999)
